### ISSUE TITLE
Bundle with @vercel/ncc 

### ISSUE THREAD

**Issue by erikyo** [fabiankaegy/monitor-wordpress-dependencies-action#3]
Do you want to avoid publishing the whole `node_modules` folder? 
Just use this [@vercel/ncc](https://github.com/vercel/ncc) in order to compile the whole node module to a single file  (it is really handy for that) 

Then add a script like this to your package.json
`"package": "ncc build index.js -o dist --license LICENSE",`

if you need to take a peek
https://github.com/erikyo/tsdoc-action

**Comment by fabiankaegy** [comment]
Thanks for the suggestion :) took me a while to get to it but finally moved to using it :)
